# Generated by Django 4.1.6 on 2023-02-10 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0003_alter_tweet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('sentiment', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('tweet_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database_manager.tweet')),
            ],
        ),
    ]
