# Generated by Django 4.1.6 on 2023-02-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0004_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='tweet_id',
            new_name='tweet',
        ),
    ]
