# Generated by Django 4.1.6 on 2023-02-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0007_alter_tweet_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rule',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
