# Generated by Django 4.1.6 on 2023-02-12 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0009_user_rule_alter_tweet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='follow_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
