# Generated by Django 4.1.6 on 2023-02-17 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0010_rename_follow_user_rule_user_alter_tweet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database_manager.user'),
        ),
    ]
